apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web
  labels:
    app: apache-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-web
  template:
    metadata:
      labels:
        app: apache-web
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80

